services:
  # Backend API Service
  - type: web
    name: college-event-portal-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: MONGODB_URI
        value: mongodb+srv://rajanvish2005:Ay2b3vylXNW53ghv@cluster1.4yireiy.mongodb.net/college-events
      - key: CLIENT_URL
        value: https://college-event-portal-frontend.onrender.com
