services:
  # Backend API Service
  - type: web
    name: college-event-portal-api
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: MONGODB_URI
        value: mongodb+srv://rajanvish2005:Ay2b3vylXNW53ghv@cluster1.4yireiy.mongodb.net/college-events
      - key: CLIENT_URL
        value: https://college-event-portal-frontend.onrender.com

  # Frontend Static Service
  - type: static
    name: college-event-portal-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: VITE_API_URL
        value: https://college-event-portal-api.onrender.com/api
